---
platform: linux

image_resource:
  type: docker-image
  source: { repository: maven }

inputs:
  - name: {{project_name}}

outputs:
  - name: test-results

params:
  project_name: jbehave-minimal-example

run:
  path: ((project_name))/ci/scripts/exec-hsm-tests.sh
