---
platform: linux

image_resource:
  type: docker-image
  source: { repository: maven }

inputs:
  - name: jbehave-minimal-example

outputs:
  - name: test-results

run:
  path: jbehave-minimal-example/ci/scripts/exec-hsm-tests.sh
