---
platform: linux

image_resource:
  type: docker-image
  source: { repository: maven }

inputs:
  - name: jbehave-minimal-example

outputs:
  - name: test-results

params:
  project_name: jbehave-minimal-example

run:
  path: jbehave-minimal-example/ci/scripts/exec-hsm-tests.sh # it seems ((project_name))/ci/scripts/exec-hsm-tests.sh does not work currently
