resources:
- name: {{project_name}}
  type: git
  source:
    uri: https://github.com/SamuelBucheliZ/{{project_name}}.git
#- name: nightly
#  type: time
#  source:
#    location: Europe/Zurich
#    interval: 1h
#    start: 01:00
#    stop: 02:00

jobs:
- name: run-hsm-tests
  plan:
  - get: {{project_name}}
#  - get: nightly
#    trigger: true
  - task: exec-hsm-tests
    file: {{project_name}}/ci/tasks/exec-hsm-tests.yml

